spring:
  profiles:
    active: dev
swagger:
  production: false
  basic:
    enable: false
    username: jeecg
    password: jeecg1314
keycloak-master:
    auth-server-url: http://39.100.234.118:8187/auth
    client-id: admin-cli
    password: admin
    realm: master
    username: admin
canal:
  client:
    instances:
      example:
        host: 47.104.96.151
        port: 11111
        batchSize: 1000